//! Build script for `outbe-l2-zk-canonical` — **read-only** codegen over
//! committed files. It does not run `nargo` or `bb`: compiling a root and
//! proving that its committed key came from its committed source is
//! `cargo xtask l2 verify`, a separate, reviewed step. This script only reads
//! what that step left behind, so `cargo build` works with no Noir toolchain.
//!
//! Inputs:
//!   * `claims/<claim>/abi.json` — the claim's public-input ABI. The public
//!     half of a Noir ABI document and nothing else; one source of truth for
//!     the generated `PublicInputs` and for every root that serves the claim.
//!   * `l2/manifest.toml` — the append-only L2 registry: a global
//!     `proof_system` plus one `[[l2_circuit]]` per `(chain_id, claim,
//!     version)` with `status` and a crate-relative `root`.
//!   * `<root>/abi.json` and `<root>/circuit.vk` — the compiled ABI and the
//!     verification key L1 verifies with.
//!
//! Output (`$OUT_DIR/l2_generated.rs`):
//!   * `enum Claim` over the claim names;
//!   * `pub mod <claim>` per claim — `PUBLIC_INPUT_COUNT`, `PublicInputs`,
//!     `public_words`, `decode_public_inputs(combined, vk)` and an `alloy`
//!     mirror with conversions in both directions;
//!   * with the `l2-keys` feature (default): `L2_KEYS` sorted by
//!     `(chain_id, claim)` and `l2_keys(chain_id, claim)`.
//!
//! Without `l2-keys` the manifest and the roots are never opened: the claim
//! ABIs still generate, the registry does not. That is the claim-only build,
//! and it is why registering an L2 changes none of the bytes this crate
//! contributes to such a consumer.
//!
//! Every check below is a hard build failure naming the entry it fired on.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;
use tiny_keccak::{Hasher, Keccak};

/// The proof system the registered keys verify under. Must equal
/// `proof_system` in `outbe-zk-canonical/circuits/manifest.toml` and the `bb`
/// pin in `mise.toml`. Asserting it across crates is the demo crate's job —
/// it is the one place the L1 and L2 sides meet, and this crate deliberately
/// has no dependency on the L1 one.
const PROOF_SYSTEM: &str = "bb-keccak-v1";

/// A `bb-keccak-v1` key is exactly 59 words: three metadata words followed by
/// 28 two-word commitments.
const VK_WORDS: usize = 3 + 28 * 2;

/// The eight `DefaultIO` pairing-accumulator words bb counts in the key
/// header's public-input count on top of the circuit's own.
const PAIRING_WORDS: usize = 8;

/// One claim: its directory name and the public parameters of its ABI.
struct ClaimAbi {
    name: String,
    params: Vec<Value>,
}

/// One non-revoked `[[l2_circuit]]` entry and its derived key identity.
struct Entry {
    chain_id: u64,
    claim: usize,
    version: String,
    status: String,
    root: String,
    vk_hash: [u8; 32],
}

fn main() {
    let dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let claims = load_claims(&dir);

    let mut generated = String::from(
        "// @generated by build.rs from claims/*/abi.json and l2/manifest.toml.\n\
         // Do not edit; edit those files and rebuild.\n\n",
    );
    generated.push_str(&generate_claim_enum(&claims));
    for claim in &claims {
        generated.push_str(&generate_claim_module(claim));
    }
    // The registry half. Without `l2-keys` the manifest, the roots and their
    // keys are not read at all and no key-table code is emitted, so nothing a
    // registration touches can reach the object file. The claim ABIs above are
    // read either way: they need no key and they are the contract every claim
    // consumer shares.
    if env::var_os("CARGO_FEATURE_L2_KEYS").is_some() {
        let entries = load_entries(&dir, &claims);
        generated.push_str(&generate_key_table(&claims, &entries));
    }

    fs::write(out.join("l2_generated.rs"), generated).expect("write l2_generated.rs");
}

// ---------------------------------------------------------------- inputs ---

/// Read every `claims/<name>/abi.json`, sorted by name. The sort is what makes
/// the generated `Claim` enum's derived `Ord` agree with the key table's sort.
fn load_claims(dir: &Path) -> Vec<ClaimAbi> {
    let claims_dir = dir.join("claims");
    println!("cargo:rerun-if-changed={}", claims_dir.display());

    let mut names: Vec<String> = fs::read_dir(&claims_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", claims_dir.display()))
        .map(|entry| entry.expect("claims dir entry").file_name())
        .map(|name| name.to_string_lossy().into_owned())
        .filter(|name| claims_dir.join(name).is_dir())
        .collect();
    names.sort();
    assert!(
        !names.is_empty(),
        "claims/ is empty; the crate needs at least one claim ABI"
    );

    names
        .into_iter()
        .map(|name| {
            let path = claims_dir.join(&name).join("abi.json");
            println!("cargo:rerun-if-changed={}", path.display());
            let abi: Value = serde_json::from_str(
                &fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display())),
            )
            .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

            let params = abi["parameters"]
                .as_array()
                .unwrap_or_else(|| panic!("claims/{name}/abi.json: `parameters` must be an array"))
                .clone();
            assert!(
                !params.is_empty(),
                "claims/{name}/abi.json: a claim exposes at least one public parameter"
            );
            for p in &params {
                assert_eq!(
                    p["visibility"].as_str(),
                    Some("public"),
                    "claims/{name}/abi.json: parameter {} is {:?}; a claim ABI is the public half of a Noir ABI and nothing else",
                    p["name"],
                    p["visibility"]
                );
            }
            ClaimAbi { name, params }
        })
        .collect()
}

/// Read `l2/manifest.toml`, check every entry, and return the non-revoked ones
/// sorted by `(chain_id, claim, version)`.
fn load_entries(dir: &Path, claims: &[ClaimAbi]) -> Vec<Entry> {
    let path = dir.join("l2/manifest.toml");
    println!("cargo:rerun-if-changed={}", path.display());
    let manifest: toml::Value = toml::from_str(
        &fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display())),
    )
    .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

    let proof_system = manifest
        .get("proof_system")
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("l2/manifest.toml: `proof_system` is required"));
    assert_eq!(
        proof_system, PROOF_SYSTEM,
        "l2/manifest.toml: proof_system {proof_system:?} != the pinned {PROOF_SYSTEM:?}"
    );

    let circuits = manifest
        .get("l2_circuit")
        .map(|v| {
            v.as_array()
                .unwrap_or_else(|| {
                    panic!("l2/manifest.toml: `l2_circuit` must be an array of tables")
                })
                .as_slice()
        })
        .unwrap_or(&[]);

    let mut seen = BTreeSet::new();
    let mut entries = Vec::new();
    for (i, c) in circuits.iter().enumerate() {
        // Every field is read by name with the entry's ordinal in the message:
        // a `[[l2_circuit]]` missing a key must say which one, not panic inside
        // a toml index.
        let chain_id = u64::try_from(
            c.get("chain_id")
                .and_then(toml::Value::as_integer)
                .unwrap_or_else(|| {
                    panic!("l2/manifest.toml: [[l2_circuit]] #{i} has no integer `chain_id`")
                }),
        )
        .unwrap_or_else(|_| {
            panic!("l2/manifest.toml: [[l2_circuit]] #{i} has a negative `chain_id`")
        });
        let claim = string(c, i, "claim");
        let version = string(c, i, "version");
        let status = string(c, i, "status");
        let root = string(c, i, "root");
        let at = format!("{chain_id}/{claim}/{version}");

        assert!(
            matches!(status.as_str(), "active" | "deprecated" | "revoked"),
            "{at}: status {status:?} must be \"active\", \"deprecated\" or \"revoked\""
        );
        assert!(
            seen.insert((chain_id, claim.clone(), version.clone())),
            "l2/manifest.toml: duplicate entry {at} — (chain_id, claim, version) must be unique"
        );

        let root_dir = dir.join(&root);
        if status == "revoked" {
            assert!(
                !root_dir.exists(),
                "{at}: entry is revoked but {root} still exists; revocation deletes the root in the same pull request"
            );
            continue;
        }

        let index = claims
            .iter()
            .position(|k| k.name == claim)
            .unwrap_or_else(|| panic!("{at}: claims/{claim}/abi.json not found; the manifest entry names claim {claim:?}"));

        for file in ["Nargo.toml", "abi.json", "circuit.vk"] {
            assert!(root_dir.join(file).exists(), "{at}: {root}/{file} missing");
        }
        check_hygiene(&at, &root_dir);
        let abi_path = root_dir.join("abi.json");
        let vk_path = root_dir.join("circuit.vk");
        println!("cargo:rerun-if-changed={}", abi_path.display());
        println!("cargo:rerun-if-changed={}", vk_path.display());

        let root_abi: Value = serde_json::from_str(
            &fs::read_to_string(&abi_path)
                .unwrap_or_else(|e| panic!("read {}: {e}", abi_path.display())),
        )
        .unwrap_or_else(|e| panic!("parse {}: {e}", abi_path.display()));
        check_public_abi(&at, &root_abi, &claims[index]);

        let vk = fs::read(&vk_path).unwrap_or_else(|e| panic!("read {}: {e}", vk_path.display()));
        check_vk(&at, &vk, field_count(&claims[index]));

        entries.push(Entry {
            chain_id,
            claim: index,
            version,
            status,
            root,
            vk_hash: keccak256(&vk),
        });
    }

    entries.sort_by(|a, b| {
        (a.chain_id, a.claim, version_key(&a.version)).cmp(&(
            b.chain_id,
            b.claim,
            version_key(&b.version),
        ))
    });
    entries
}

fn string(entry: &toml::Value, index: usize, key: &str) -> String {
    entry
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| {
            panic!("l2/manifest.toml: [[l2_circuit]] #{index} has no string `{key}`")
        })
        .to_string()
}

// ---------------------------------------------------------------- checks ---

/// The root's public parameters must equal the claim ABI by name, type and
/// order. An L2 that exposes a different layout is proving a different claim.
fn check_public_abi(at: &str, root_abi: &Value, claim: &ClaimAbi) {
    let name = &claim.name;
    let public: Vec<&Value> = root_abi["parameters"]
        .as_array()
        .unwrap_or_else(|| panic!("{at}: abi.json `parameters` must be an array"))
        .iter()
        .filter(|p| p["visibility"] == "public")
        .collect();

    assert_eq!(
        public.len(),
        claim.params.len(),
        "{at}: root exposes {} public parameters, claim {name:?} declares {}",
        public.len(),
        claim.params.len()
    );
    for (index, (got, want)) in public.iter().zip(&claim.params).enumerate() {
        assert_eq!(
            got["name"], want["name"],
            "{at}: public parameter {index} is named {}, claim {name:?} declares {}",
            got["name"], want["name"]
        );
        assert_eq!(
            got["type"], want["type"],
            "{at}: public parameter {index} {} has type {}, claim {name:?} declares {}",
            got["name"], got["type"], want["type"]
        );
    }
}

/// Root hygiene, the half that needs no toolchain: the package is a `bin`, no
/// `path` dependency resolves outside the root, and every git dependency is
/// pinned. `cargo xtask l2 verify` checks the same rules, but only CI runs it,
/// so without this a root that silently depends on code outside itself still
/// builds its key into the table.
fn check_hygiene(at: &str, root_dir: &Path) {
    let path = root_dir.join("Nargo.toml");
    println!("cargo:rerun-if-changed={}", path.display());
    let nargo: toml::Value = toml::from_str(
        &fs::read_to_string(&path).unwrap_or_else(|e| panic!("{at}: read {}: {e}", path.display())),
    )
    .unwrap_or_else(|e| panic!("{at}: parse {}: {e}", path.display()));

    assert_eq!(
        nargo
            .get("package")
            .and_then(|p| p.get("type"))
            .and_then(|t| t.as_str()),
        Some("bin"),
        "{at}: Nargo.toml [package] type must be \"bin\""
    );

    let canonical = fs::canonicalize(root_dir)
        .unwrap_or_else(|e| panic!("{at}: canonicalize {}: {e}", root_dir.display()));
    let Some(deps) = nargo.get("dependencies").and_then(|d| d.as_table()) else {
        return;
    };
    for (name, dep) in deps {
        if let Some(rel) = dep.get("path").and_then(|p| p.as_str()) {
            let target = fs::canonicalize(root_dir.join(rel)).unwrap_or_else(|_| {
                panic!("{at}: dependency {name:?} path {rel:?} does not exist")
            });
            assert!(
                target.starts_with(&canonical),
                "{at}: dependency {name:?} has path {rel:?} escaping the root; \
                 an L2 root is self-contained so nothing can change under it"
            );
        }
        if dep.get("git").is_some() {
            assert!(
                dep.get("tag").is_some() || dep.get("rev").is_some(),
                "{at}: dependency {name:?} is a git dependency without a tag or rev; pin it"
            );
        }
    }
}

/// The cheap half of key verification, which needs no toolchain: the key is
/// the right size and its header declares the claim's public inputs. Byte
/// equality against a recompile is `cargo xtask l2 verify`.
fn check_vk(at: &str, vk: &[u8], public_input_count: usize) {
    assert_eq!(
        vk.len(),
        VK_WORDS * 32,
        "{at}: circuit.vk is {} bytes; a {PROOF_SYSTEM} key is {} ({VK_WORDS} words)",
        vk.len(),
        VK_WORDS * 32
    );
    let word = &vk[32..64];
    assert!(
        word[..28].iter().all(|&b| b == 0),
        "{at}: circuit.vk header word 1 is not a u32"
    );
    let declared = u32::from_be_bytes(word[28..].try_into().expect("four bytes")) as usize;
    assert_eq!(
        declared,
        public_input_count + PAIRING_WORDS,
        "{at}: circuit.vk header declares {declared} public inputs; the claim ABI has {public_input_count} (+{PAIRING_WORDS} pairing accumulator words)"
    );
}

// ------------------------------------------------------------- code gen ----

fn generate_claim_enum(claims: &[ClaimAbi]) -> String {
    let variants: String = claims
        .iter()
        .map(|c| {
            format!(
                "    /// `claims/{}/abi.json`.\n    {},\n",
                c.name,
                type_ident(&c.name)
            )
        })
        .collect();
    let arms: String = claims
        .iter()
        .map(|c| {
            format!(
                "            Claim::{} => {:?},\n",
                type_ident(&c.name),
                c.name
            )
        })
        .collect();
    format!(
        "/// The claims this crate knows, one per `claims/<name>/abi.json`.\n\
         ///\n\
         /// Variants are in claim-name order, so the derived `Ord` matches the\n\
         /// sort of [`L2_KEYS`] and the binary search in [`l2_keys`].\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         pub enum Claim {{\n{variants}}}\n\n\
         impl Claim {{\n\
         \x20   /// The claim's directory name, as `l2/manifest.toml` spells it.\n\
         \x20   pub const fn as_str(self) -> &'static str {{\n\
         \x20       match self {{\n{arms}        }}\n    }}\n}}\n\n"
    )
}

fn generate_claim_module(claim: &ClaimAbi) -> String {
    let name = &claim.name;
    let variant = type_ident(name);
    let count = field_count(claim);

    let mut fields = String::new();
    let mut alloy_fields = String::new();
    let mut to_alloy = String::new();
    let mut from_alloy = String::new();
    let mut words = Vec::new();
    let mut decoded = String::new();
    let mut index = 0usize;
    for p in &claim.params {
        let field = p["name"].as_str().expect("ABI parameter name");
        let ty = &p["type"];
        fields.push_str(&format!("        pub {field}: {},\n", rust_type(ty, name)));
        alloy_fields.push_str(&format!(
            "            pub {field}: {},\n",
            alloy_type(ty, name)
        ));
        to_alloy.push_str(&format!(
            "                    {field}: {},\n",
            circuit_to_alloy(ty, &format!("value.{field}"))
        ));
        from_alloy.push_str(&format!(
            "                    {field}: {},\n",
            alloy_to_circuit(ty, &format!("value.{field}"))
        ));
        words.extend(leaves(ty, &format!("p.{field}"), name));
        decoded.push_str(&format!(
            "            {field}: {},\n",
            decode_expr(ty, index, name)
        ));
        index += leaves(ty, "_", name).len();
    }
    let words = words.join(",\n            ");
    let from_field = if decoded.contains("::from_field") {
        "        use outbe_zk_core::FieldElement;\n"
    } else {
        ""
    };

    format!(
        r#"/// The `{name}` claim, generated from `claims/{name}/abi.json`.
pub mod {name} {{
    use alloy_primitives::B256;
    use ark_bn254::Fr;

    /// Which claim this module is.
    pub const CLAIM: super::Claim = super::Claim::{variant};

    /// Number of public field words a proof of this claim exposes.
    pub const PUBLIC_INPUT_COUNT: usize = {count};

    /// Public inputs, in ABI order.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct PublicInputs {{
{fields}    }}

    /// Flatten to ABI-ordered field words — what a prover hands the backend
    /// and what [`crate::encode_combined_proof`] takes.
    pub fn public_words(p: &PublicInputs) -> [Fr; PUBLIC_INPUT_COUNT] {{
        [
            {words},
        ]
    }}

    /// Decode the public inputs prefixed to a combined proof.
    ///
    /// The expected length comes from the key header rather than a constant,
    /// so this one decoder serves every key registered for the claim — any
    /// chain, any version, any circuit size.
    pub fn decode_public_inputs(
        combined_proof: &[u8],
        vk: &[u8],
    ) -> Result<PublicInputs, outbe_zk_core::Error> {{
{from_field}        let expected = crate::combined_len(vk, PUBLIC_INPUT_COUNT)?;
        let words =
            outbe_zk_core::zkproof::decode_public_words::<PUBLIC_INPUT_COUNT>(combined_proof, expected)?;
        let fields = words.map(|word| outbe_zk_core::codec::field_from_be_bytes(&word));
        Ok(PublicInputs {{
{decoded}        }})
    }}

    /// The same public inputs as Ethereum ABI values.
    pub mod alloy {{
        use alloy_primitives::B256;
        use ark_bn254::Fr;

        /// Public inputs, in ABI order.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct PublicInputs {{
{alloy_fields}        }}

        impl TryFrom<super::PublicInputs> for PublicInputs {{
            type Error = outbe_zk_core::Error;

            /// Reject field words that would not fit a 32-byte ABI value.
            fn try_from(value: super::PublicInputs) -> Result<Self, Self::Error> {{
                Ok(Self {{
{to_alloy}                }})
            }}
        }}

        impl TryFrom<PublicInputs> for super::PublicInputs {{
            type Error = outbe_zk_core::Error;

            /// Reject field words at or above the modulus instead of reducing.
            fn try_from(value: PublicInputs) -> Result<Self, Self::Error> {{
                Ok(Self {{
{from_alloy}                }})
            }}
        }}
    }}
}}

"#
    )
}

fn generate_key_table(claims: &[ClaimAbi], entries: &[Entry]) -> String {
    let mut table = String::new();
    let mut cursor = 0;
    while cursor < entries.len() {
        let head = &entries[cursor];
        let mut keys = String::new();
        while cursor < entries.len()
            && entries[cursor].chain_id == head.chain_id
            && entries[cursor].claim == head.claim
        {
            let e = &entries[cursor];
            keys.push_str(&format!(
                "        crate::L2Key {{\n\
                 \x20           version: {:?},\n\
                 \x20           status: crate::CircuitStatus::{},\n\
                 \x20           vk_hash: ::hex_literal::hex!({:?}),\n\
                 \x20           vk_bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}/circuit.vk\")),\n\
                 \x20       }},\n",
                e.version,
                type_ident(&e.status),
                hex_str(&e.vk_hash),
                e.root,
            ));
            cursor += 1;
        }
        table.push_str(&format!(
            "    crate::L2ClaimEntry {{\n\
             \x20       chain_id: {},\n\
             \x20       claim: Claim::{},\n\
             \x20       keys: &[\n{keys}        ],\n\
             \x20   }},\n",
            head.chain_id,
            type_ident(&claims[head.claim].name),
        ));
    }

    format!(
        "/// Every registered, non-revoked L2 key, sorted by `(chain_id, claim)`;\n\
         /// the keys of one pair are in ascending version order.\n\
         pub const L2_KEYS: &[crate::L2ClaimEntry] = &[\n{table}];\n\n\
         /// The keys registered for one L2 chain and claim, newest version last,\n\
         /// or an empty slice if the pair has no registration.\n\
         ///\n\
         /// This is the only way a key reaches the verifier: the table is\n\
         /// `&'static`, built from `l2/manifest.toml` at compile time, so no key\n\
         /// can be added at runtime, from calldata or from storage.\n\
         pub fn l2_keys(chain_id: u64, claim: Claim) -> &'static [crate::L2Key] {{\n\
         \x20   L2_KEYS\n\
         \x20       .binary_search_by_key(&(chain_id, claim), |entry| (entry.chain_id, entry.claim))\n\
         \x20       .map_or(&[], |index| L2_KEYS[index].keys)\n}}\n"
    )
}

// ------------------------------------------------------------ ABI types ----

// ponytail: the generator handles `field`, unsigned `integer` and arrays of
// those — every shape a claim ABI uses today, plus the obvious next one. A
// claim that needs an EthAddress, a limbed `U256` or a multi-field struct as a
// public word gets a clear build failure here; lift the arms from
// `outbe-zk-canonical/build.rs`, which already has them, when one does.

/// Every leaf field word of one ABI parameter, as Rust expressions.
fn leaves(ty: &Value, expr: &str, claim: &str) -> Vec<String> {
    match ty["kind"].as_str() {
        Some("field") => vec![expr.to_string()],
        Some("integer") => vec![format!("Fr::from({expr} as u128)")],
        Some("array") => {
            let len = ty["length"].as_u64().expect("array length");
            (0..len)
                .flat_map(|i| leaves(&ty["type"], &format!("{expr}[{i}]"), claim))
                .collect()
        }
        _ => panic!("claim {claim:?}: unsupported public ABI type: {ty}"),
    }
}

/// Leaf count of a whole claim ABI.
fn field_count(claim: &ClaimAbi) -> usize {
    claim
        .params
        .iter()
        .map(|p| leaves(&p["type"], "_", &claim.name).len())
        .sum()
}

fn rust_type(ty: &Value, claim: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => "Fr".to_string(),
        Some("integer") => {
            let sign = ty["sign"].as_str().unwrap_or("unsigned");
            assert_eq!(
                sign, "unsigned",
                "claim {claim:?}: signed integers are not a public ABI type"
            );
            format!("u{}", ty["width"].as_u64().expect("integer width"))
        }
        Some("array") => {
            let inner = &ty["type"];
            assert!(
                matches!(inner["kind"].as_str(), Some("field" | "integer")),
                "claim {claim:?}: only arrays of field or integer are a public ABI type, got {inner}"
            );
            format!(
                "[{}; {}]",
                rust_type(inner, claim),
                ty["length"].as_u64().expect("array length")
            )
        }
        _ => panic!("claim {claim:?}: unsupported public ABI type: {ty}"),
    }
}

/// The same shape with field words as `B256`; integers keep their Rust type.
fn alloy_type(ty: &Value, claim: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => "B256".to_string(),
        Some("array") => format!(
            "[{}; {}]",
            alloy_type(&ty["type"], claim),
            ty["length"].as_u64().expect("array length")
        ),
        _ => rust_type(ty, claim),
    }
}

/// Convert one parameter to its Ethereum ABI form. Integers are identical in
/// both representations, so only field words need converting; `rust_type` has
/// already rejected anything else.
fn circuit_to_alloy(ty: &Value, expr: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => format!("outbe_zk_core::codec::field_to_b256(&{expr})?"),
        Some("array") if ty["type"]["kind"] == "field" => format!(
            "{{ let mut out = [B256::ZERO; {}]; \
             for (slot, value) in out.iter_mut().zip({expr}.iter()) {{ \
             *slot = outbe_zk_core::codec::field_to_b256(value)?; }} out }}",
            ty["length"].as_u64().expect("array length")
        ),
        _ => expr.to_string(),
    }
}

/// The reverse, rejecting field words at or above the modulus.
fn alloy_to_circuit(ty: &Value, expr: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => format!("outbe_zk_core::codec::field_from_b256(&{expr})?"),
        Some("array") if ty["type"]["kind"] == "field" => format!(
            "{{ let mut out = [Fr::from(0u64); {}]; \
             for (slot, value) in out.iter_mut().zip({expr}.iter()) {{ \
             *slot = outbe_zk_core::codec::field_from_b256(value)?; }} out }}",
            ty["length"].as_u64().expect("array length")
        ),
        _ => expr.to_string(),
    }
}

/// One parameter's value, rebuilt from `fields[..]` inside the decoder.
fn decode_expr(ty: &Value, index: usize, claim: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => format!("fields[{index}]"),
        Some("integer") => format!("{}::from_field(&fields[{index}])?", rust_type(ty, claim)),
        Some("array") if ty["type"]["kind"] == "field" => {
            format!("std::array::from_fn(|i| fields[{index} + i])")
        }
        Some("array") => {
            let inner = &ty["type"];
            let stride = leaves(inner, "_", claim).len();
            let exprs: Vec<String> = (0..ty["length"].as_u64().expect("array length") as usize)
                .map(|i| decode_expr(inner, index + i * stride, claim))
                .collect();
            format!("[{}]", exprs.join(", "))
        }
        _ => panic!("claim {claim:?}: unsupported public ABI type: {ty}"),
    }
}

// --------------------------------------------------------------- helpers ---

/// `tribute` -> `Tribute`, `active` -> `Active`, `tribute_v2` -> `TributeV2`.
fn type_ident(name: &str) -> String {
    name.split('_')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Parse `"a.b.c"` into a comparable tuple (missing parts = 0).
fn version_key(v: &str) -> (u64, u64, u64) {
    let mut parts = v.split('.').map(|p| p.parse::<u64>().unwrap_or(0));
    (
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
    )
}

fn keccak256(input: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak::v256();
    hasher.update(input);
    let mut out = [0u8; 32];
    hasher.finalize(&mut out);
    out
}

fn hex_str(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
