//! Build script for `outbe-l2-zk-canonical` — **read-only** codegen over
//! committed files. It does not run `nargo` or `bb`: compiling a root and
//! proving that its committed key came from its committed source is
//! `cargo xtask l2 verify`, a separate, reviewed step. This script only reads
//! what that step left behind, so `cargo build` works with no Noir toolchain.
//!
//! Inputs:
//!   * `outbe_l2_claims::CLAIM_ABIS` — each claim's public-input ABI, read
//!     from the crate that owns it. A build script cannot open another
//!     package's files by path, so `outbe-l2-claims` is a build-dependency as
//!     well as a normal one and exposes its `claims/<claim>/abi.json`
//!     documents as `include_str!` consts.
//!   * `l2/manifest.toml` — the append-only L2 registry: a global
//!     `proof_system` plus one `[[l2_circuit]]` per `(chain_id, claim,
//!     version)` with `status` and a crate-relative `root`.
//!   * `<root>/abi.json` and `<root>/circuit.vk` — the compiled ABI and the
//!     verification key L1 verifies with.
//!
//! Output (`$OUT_DIR/l2_generated.rs`):
//!   * `enum Claim` over the claim names;
//!   * `claims::<claim>` per claim — the contract re-exported from
//!     `outbe-l2-claims`, plus `CLAIM` and the key-aware
//!     `decode_public_inputs(combined, vk)`, which lives here because the
//!     expected proof length comes from the verification key;
//!   * `L2_KEYS` sorted by `(chain_id, claim)` and `l2_keys(chain_id, claim)`.
//!
//! Every check below is a hard build failure naming the entry it fired on.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;
use tiny_keccak::{Hasher, Keccak};

/// The proof system the registered keys verify under. Must equal
/// `proof_system` in `outbe-zk-canonical/circuits/manifest.toml` and the `bb`
/// pin in `mise.toml`. Asserting it across crates is the demo crate's job —
/// it is the one place the L1 and L2 sides meet, and this crate deliberately
/// has no dependency on the L1 one.
const PROOF_SYSTEM: &str = "bb-keccak-v1";

/// A `bb-keccak-v1` key is exactly 59 words: three metadata words followed by
/// 28 two-word commitments.
const VK_WORDS: usize = 3 + 28 * 2;

/// The eight `DefaultIO` pairing-accumulator words bb counts in the key
/// header's public-input count on top of the circuit's own.
const PAIRING_WORDS: usize = 8;

/// One claim: its directory name, the public parameters of its ABI and the
/// leaf-word count both derived from `outbe-l2-claims`.
struct ClaimAbi {
    name: &'static str,
    params: Vec<Value>,
    public_input_count: usize,
}

/// One non-revoked `[[l2_circuit]]` entry and its derived key identity.
struct Entry {
    chain_id: u64,
    claim: usize,
    version: String,
    status: String,
    root: String,
    vk_hash: [u8; 32],
}

fn main() {
    let dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let claims = load_claims();
    let entries = load_entries(&dir, &claims);

    let mut generated = String::from(
        "// @generated by build.rs from outbe_l2_claims::CLAIM_ABIS and l2/manifest.toml.\n\
         // Do not edit; edit those files and rebuild.\n\n",
    );
    generated.push_str(&generate_claim_enum(&claims));
    generated.push_str(&generate_claims_module(&claims));
    generated.push_str(&generate_key_table(&claims, &entries));

    fs::write(out.join("l2_generated.rs"), generated).expect("write l2_generated.rs");
}

// ---------------------------------------------------------------- inputs ---

/// Parse every claim ABI `outbe-l2-claims` exposes.
///
/// The contract arrives as `include_str!`d JSON rather than as a path this
/// script opens: the crate that owns `claims/<name>/abi.json` is the crate
/// that ships it, and a build script cannot reach another package's files.
fn load_claims() -> Vec<ClaimAbi> {
    let claims: Vec<ClaimAbi> = outbe_l2_claims::CLAIM_ABIS
        .iter()
        .map(|claim| {
            let name = claim.name;
            let abi: Value = serde_json::from_str(claim.abi_json)
                .unwrap_or_else(|e| panic!("parse the {name} claim ABI: {e}"));
            let params = abi["parameters"]
                .as_array()
                .unwrap_or_else(|| panic!("the {name} claim ABI: `parameters` must be an array"))
                .clone();
            ClaimAbi {
                name,
                params,
                public_input_count: claim.public_input_count,
            }
        })
        .collect();

    assert!(!claims.is_empty(), "outbe-l2-claims exposes no claim ABI");
    // The generated `Claim` enum's derived `Ord` is what the key table is
    // sorted by and what `l2_keys` binary-searches, so the claim-name order
    // `outbe-l2-claims` emits is load-bearing here, not cosmetic.
    assert!(
        claims.windows(2).all(|w| w[0].name < w[1].name),
        "outbe_l2_claims::CLAIM_ABIS is not sorted by claim name"
    );
    claims
}

/// Read `l2/manifest.toml`, check every entry, and return the non-revoked ones
/// sorted by `(chain_id, claim, version)`.
fn load_entries(dir: &Path, claims: &[ClaimAbi]) -> Vec<Entry> {
    let path = dir.join("l2/manifest.toml");
    println!("cargo:rerun-if-changed={}", path.display());
    let manifest: toml::Value = toml::from_str(
        &fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display())),
    )
    .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

    let proof_system = manifest
        .get("proof_system")
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("l2/manifest.toml: `proof_system` is required"));
    assert_eq!(
        proof_system, PROOF_SYSTEM,
        "l2/manifest.toml: proof_system {proof_system:?} != the pinned {PROOF_SYSTEM:?}"
    );

    let circuits = manifest
        .get("l2_circuit")
        .map(|v| {
            v.as_array()
                .unwrap_or_else(|| {
                    panic!("l2/manifest.toml: `l2_circuit` must be an array of tables")
                })
                .as_slice()
        })
        .unwrap_or(&[]);

    let mut seen = BTreeSet::new();
    let mut entries = Vec::new();
    for (i, c) in circuits.iter().enumerate() {
        // Every field is read by name with the entry's ordinal in the message:
        // a `[[l2_circuit]]` missing a key must say which one, not panic inside
        // a toml index.
        let chain_id = u64::try_from(
            c.get("chain_id")
                .and_then(toml::Value::as_integer)
                .unwrap_or_else(|| {
                    panic!("l2/manifest.toml: [[l2_circuit]] #{i} has no integer `chain_id`")
                }),
        )
        .unwrap_or_else(|_| {
            panic!("l2/manifest.toml: [[l2_circuit]] #{i} has a negative `chain_id`")
        });
        let claim = string(c, i, "claim");
        let version = string(c, i, "version");
        let status = string(c, i, "status");
        let root = string(c, i, "root");
        let at = format!("{chain_id}/{claim}/{version}");

        assert!(
            matches!(status.as_str(), "active" | "deprecated" | "revoked"),
            "{at}: status {status:?} must be \"active\", \"deprecated\" or \"revoked\""
        );
        assert!(
            seen.insert((chain_id, claim.clone(), version.clone())),
            "l2/manifest.toml: duplicate entry {at} — (chain_id, claim, version) must be unique"
        );

        let root_dir = dir.join(&root);
        if status == "revoked" {
            assert!(
                !root_dir.exists(),
                "{at}: entry is revoked but {root} still exists; revocation deletes the root in the same pull request"
            );
            continue;
        }

        let index = claims
            .iter()
            .position(|k| k.name == claim.as_str())
            .unwrap_or_else(|| panic!("{at}: claims/{claim}/abi.json not found; the manifest entry names claim {claim:?}"));

        for file in ["Nargo.toml", "abi.json", "circuit.vk"] {
            assert!(root_dir.join(file).exists(), "{at}: {root}/{file} missing");
        }
        check_hygiene(&at, &root_dir);
        let abi_path = root_dir.join("abi.json");
        let vk_path = root_dir.join("circuit.vk");
        println!("cargo:rerun-if-changed={}", abi_path.display());
        println!("cargo:rerun-if-changed={}", vk_path.display());

        let root_abi: Value = serde_json::from_str(
            &fs::read_to_string(&abi_path)
                .unwrap_or_else(|e| panic!("read {}: {e}", abi_path.display())),
        )
        .unwrap_or_else(|e| panic!("parse {}: {e}", abi_path.display()));
        check_public_abi(&at, &root_abi, &claims[index]);

        let vk = fs::read(&vk_path).unwrap_or_else(|e| panic!("read {}: {e}", vk_path.display()));
        check_vk(&at, &vk, claims[index].public_input_count);

        entries.push(Entry {
            chain_id,
            claim: index,
            version,
            status,
            root,
            vk_hash: keccak256(&vk),
        });
    }

    entries.sort_by(|a, b| {
        (a.chain_id, a.claim, version_key(&a.version)).cmp(&(
            b.chain_id,
            b.claim,
            version_key(&b.version),
        ))
    });
    entries
}

fn string(entry: &toml::Value, index: usize, key: &str) -> String {
    entry
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| {
            panic!("l2/manifest.toml: [[l2_circuit]] #{index} has no string `{key}`")
        })
        .to_string()
}

// ---------------------------------------------------------------- checks ---

/// The root's public parameters must equal the claim ABI by name, type and
/// order. An L2 that exposes a different layout is proving a different claim.
fn check_public_abi(at: &str, root_abi: &Value, claim: &ClaimAbi) {
    let name = &claim.name;
    let public: Vec<&Value> = root_abi["parameters"]
        .as_array()
        .unwrap_or_else(|| panic!("{at}: abi.json `parameters` must be an array"))
        .iter()
        .filter(|p| p["visibility"] == "public")
        .collect();

    assert_eq!(
        public.len(),
        claim.params.len(),
        "{at}: root exposes {} public parameters, claim {name:?} declares {}",
        public.len(),
        claim.params.len()
    );
    for (index, (got, want)) in public.iter().zip(&claim.params).enumerate() {
        assert_eq!(
            got["name"], want["name"],
            "{at}: public parameter {index} is named {}, claim {name:?} declares {}",
            got["name"], want["name"]
        );
        assert_eq!(
            got["type"], want["type"],
            "{at}: public parameter {index} {} has type {}, claim {name:?} declares {}",
            got["name"], got["type"], want["type"]
        );
    }
}

/// Root hygiene, the half that needs no toolchain: the package is a `bin`, no
/// `path` dependency resolves outside the root, and every git dependency is
/// pinned. `cargo xtask l2 verify` checks the same rules, but only CI runs it,
/// so without this a root that silently depends on code outside itself still
/// builds its key into the table.
fn check_hygiene(at: &str, root_dir: &Path) {
    let path = root_dir.join("Nargo.toml");
    println!("cargo:rerun-if-changed={}", path.display());
    let nargo: toml::Value = toml::from_str(
        &fs::read_to_string(&path).unwrap_or_else(|e| panic!("{at}: read {}: {e}", path.display())),
    )
    .unwrap_or_else(|e| panic!("{at}: parse {}: {e}", path.display()));

    assert_eq!(
        nargo
            .get("package")
            .and_then(|p| p.get("type"))
            .and_then(|t| t.as_str()),
        Some("bin"),
        "{at}: Nargo.toml [package] type must be \"bin\""
    );

    let canonical = fs::canonicalize(root_dir)
        .unwrap_or_else(|e| panic!("{at}: canonicalize {}: {e}", root_dir.display()));
    let Some(deps) = nargo.get("dependencies").and_then(|d| d.as_table()) else {
        return;
    };
    for (name, dep) in deps {
        if let Some(rel) = dep.get("path").and_then(|p| p.as_str()) {
            let target = fs::canonicalize(root_dir.join(rel)).unwrap_or_else(|_| {
                panic!("{at}: dependency {name:?} path {rel:?} does not exist")
            });
            assert!(
                target.starts_with(&canonical),
                "{at}: dependency {name:?} has path {rel:?} escaping the root; \
                 an L2 root is self-contained so nothing can change under it"
            );
        }
        if dep.get("git").is_some() {
            assert!(
                dep.get("tag").is_some() || dep.get("rev").is_some(),
                "{at}: dependency {name:?} is a git dependency without a tag or rev; pin it"
            );
        }
    }
}

/// The cheap half of key verification, which needs no toolchain: the key is
/// the right size and its header declares the claim's public inputs. Byte
/// equality against a recompile is `cargo xtask l2 verify`.
fn check_vk(at: &str, vk: &[u8], public_input_count: usize) {
    assert_eq!(
        vk.len(),
        VK_WORDS * 32,
        "{at}: circuit.vk is {} bytes; a {PROOF_SYSTEM} key is {} ({VK_WORDS} words)",
        vk.len(),
        VK_WORDS * 32
    );
    let word = &vk[32..64];
    assert!(
        word[..28].iter().all(|&b| b == 0),
        "{at}: circuit.vk header word 1 is not a u32"
    );
    let declared = u32::from_be_bytes(word[28..].try_into().expect("four bytes")) as usize;
    assert_eq!(
        declared,
        public_input_count + PAIRING_WORDS,
        "{at}: circuit.vk header declares {declared} public inputs; the claim ABI has {public_input_count} (+{PAIRING_WORDS} pairing accumulator words)"
    );
}

// ------------------------------------------------------------- code gen ----

fn generate_claim_enum(claims: &[ClaimAbi]) -> String {
    let variants: String = claims
        .iter()
        .map(|c| {
            format!(
                "    /// `claims/{}/abi.json`.\n    {},\n",
                c.name,
                type_ident(c.name)
            )
        })
        .collect();
    let arms: String = claims
        .iter()
        .map(|c| {
            format!(
                "            Claim::{} => {:?},\n",
                type_ident(c.name),
                c.name
            )
        })
        .collect();
    format!(
        "/// The claims this crate knows, one per `claims/<name>/abi.json`.\n\
         ///\n\
         /// Variants are in claim-name order, so the derived `Ord` matches the\n\
         /// sort of [`L2_KEYS`] and the binary search in [`l2_keys`].\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         pub enum Claim {{\n{variants}}}\n\n\
         impl Claim {{\n\
         \x20   /// The claim's directory name, as `l2/manifest.toml` spells it.\n\
         \x20   pub const fn as_str(self) -> &'static str {{\n\
         \x20       match self {{\n{arms}        }}\n    }}\n}}\n\n"
    )
}

/// The claim modules: the contract re-exported from `outbe-l2-claims`, plus
/// the two items that need this crate — which `Claim` variant the module is,
/// and the key-aware decoder. The decoder's body is the same for every claim
/// because the ABI-shaped half of it, `from_fields`, is generated over in the
/// claims crate.
fn generate_claims_module(claims: &[ClaimAbi]) -> String {
    let modules: String = claims
        .iter()
        .map(|claim| {
            let name = claim.name;
            let variant = type_ident(name);
            format!(
                r#"    /// The `{name}` claim: the contract from `outbe-l2-claims`, plus the
    /// key-aware decoder.
    pub mod {name} {{
        pub use outbe_l2_claims::claims::{name}::*;

        /// Which claim this module is.
        pub const CLAIM: crate::Claim = crate::Claim::{variant};

        /// Decode the public inputs prefixed to a combined proof.
        ///
        /// The expected length comes from the key header rather than a
        /// constant, so this one decoder serves every key registered for the
        /// claim — any chain, any version, any circuit size. That is also why
        /// it lives with the keys rather than with the claim.
        pub fn decode_public_inputs(
            combined_proof: &[u8],
            vk: &[u8],
        ) -> Result<PublicInputs, outbe_zk_core::Error> {{
            let expected = crate::combined_len(vk, PUBLIC_INPUT_COUNT)?;
            let words = outbe_zk_core::zkproof::decode_public_words::<PUBLIC_INPUT_COUNT>(
                combined_proof,
                expected,
            )?;
            from_fields(&words.map(|word| outbe_zk_core::codec::field_from_be_bytes(&word)))
        }}
    }}

"#
            )
        })
        .collect();

    format!(
        "/// The claims, one module per `outbe-l2-claims` claim ABI.\n\
         pub mod claims {{\n{modules}}}\n\n"
    )
}

fn generate_key_table(claims: &[ClaimAbi], entries: &[Entry]) -> String {
    let mut table = String::new();
    let mut cursor = 0;
    while cursor < entries.len() {
        let head = &entries[cursor];
        let mut keys = String::new();
        while cursor < entries.len()
            && entries[cursor].chain_id == head.chain_id
            && entries[cursor].claim == head.claim
        {
            let e = &entries[cursor];
            keys.push_str(&format!(
                "        crate::L2Key {{\n\
                 \x20           version: {:?},\n\
                 \x20           status: crate::CircuitStatus::{},\n\
                 \x20           vk_hash: ::hex_literal::hex!({:?}),\n\
                 \x20           vk_bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}/circuit.vk\")),\n\
                 \x20       }},\n",
                e.version,
                type_ident(&e.status),
                hex_str(&e.vk_hash),
                e.root,
            ));
            cursor += 1;
        }
        table.push_str(&format!(
            "    crate::L2ClaimEntry {{\n\
             \x20       chain_id: {},\n\
             \x20       claim: Claim::{},\n\
             \x20       keys: &[\n{keys}        ],\n\
             \x20   }},\n",
            head.chain_id,
            type_ident(claims[head.claim].name),
        ));
    }

    format!(
        "/// Every registered, non-revoked L2 key, sorted by `(chain_id, claim)`;\n\
         /// the keys of one pair are in ascending version order.\n\
         pub const L2_KEYS: &[crate::L2ClaimEntry] = &[\n{table}];\n\n\
         /// The keys registered for one L2 chain and claim, newest version last,\n\
         /// or an empty slice if the pair has no registration.\n\
         ///\n\
         /// This is the only way a key reaches the verifier: the table is\n\
         /// `&'static`, built from `l2/manifest.toml` at compile time, so no key\n\
         /// can be added at runtime, from calldata or from storage.\n\
         pub fn l2_keys(chain_id: u64, claim: Claim) -> &'static [crate::L2Key] {{\n\
         \x20   L2_KEYS\n\
         \x20       .binary_search_by_key(&(chain_id, claim), |entry| (entry.chain_id, entry.claim))\n\
         \x20       .map_or(&[], |index| L2_KEYS[index].keys)\n}}\n"
    )
}

// --------------------------------------------------------------- helpers ---

/// `tribute` -> `Tribute`, `active` -> `Active`, `tribute_v2` -> `TributeV2`.
fn type_ident(name: &str) -> String {
    name.split('_')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Parse `"a.b.c"` into a comparable tuple (missing parts = 0).
fn version_key(v: &str) -> (u64, u64, u64) {
    let mut parts = v.split('.').map(|p| p.parse::<u64>().unwrap_or(0));
    (
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
    )
}

fn keccak256(input: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak::v256();
    hasher.update(input);
    let mut out = [0u8; 32];
    hasher.finalize(&mut out);
    out
}

fn hex_str(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
