//! Build script for `outbe-l2-claims` — **read-only** codegen over the
//! committed claim ABIs. It reads nothing but `claims/<name>/abi.json`, so no
//! key, root or manifest can reach the code it emits.
//!
//! Input:
//!   * `claims/<claim>/abi.json` — the claim's public-input ABI. The public
//!     half of a Noir ABI document and nothing else; one source of truth for
//!     the generated `PublicInputs` here and for every root that serves the
//!     claim over in `outbe-l2-zk-canonical`.
//!
//! Output (`$OUT_DIR/l2_claims_generated.rs`):
//!   * `pub mod <claim>` per claim — `PUBLIC_INPUT_COUNT`, `PublicInputs`,
//!     `public_words`, `from_fields` and an `alloy` mirror with conversions in
//!     both directions;
//!   * `CLAIM_ABIS`, each claim's ABI document as a `&'static str` plus its
//!     leaf-word count. That is how `outbe-l2-zk-canonical`'s build script
//!     reads the contract: a build script cannot open another package's files
//!     by path, so it takes this crate as a build-dependency and reads the
//!     const instead.
//!
//! Every check below is a hard build failure naming the claim it fired on.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

/// One claim: its directory name and the public parameters of its ABI.
struct ClaimAbi {
    name: String,
    params: Vec<Value>,
}

fn main() {
    let dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let claims = load_claims(&dir);

    let mut generated = String::from(
        "// @generated by build.rs from claims/*/abi.json.\n\
         // Do not edit; edit those files and rebuild.\n\n",
    );
    for claim in &claims {
        generated.push_str(&generate_claim_module(claim));
    }
    generated.push_str(&generate_claim_abis(&claims));

    fs::write(out.join("l2_claims_generated.rs"), generated).expect("write l2_claims_generated.rs");
}

// ---------------------------------------------------------------- inputs ---

/// Read every `claims/<name>/abi.json`, sorted by name. The sort is what makes
/// the `Claim` enum `outbe-l2-zk-canonical` derives from `CLAIM_ABIS` agree
/// with the sort of its key table.
fn load_claims(dir: &Path) -> Vec<ClaimAbi> {
    let claims_dir = dir.join("claims");
    println!("cargo:rerun-if-changed={}", claims_dir.display());

    let mut names: Vec<String> = fs::read_dir(&claims_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", claims_dir.display()))
        .map(|entry| entry.expect("claims dir entry").file_name())
        .map(|name| name.to_string_lossy().into_owned())
        .filter(|name| claims_dir.join(name).is_dir())
        .collect();
    names.sort();
    assert!(
        !names.is_empty(),
        "claims/ is empty; the crate needs at least one claim ABI"
    );

    names
        .into_iter()
        .map(|name| {
            let path = claims_dir.join(&name).join("abi.json");
            println!("cargo:rerun-if-changed={}", path.display());
            let abi: Value = serde_json::from_str(
                &fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display())),
            )
            .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

            let params = abi["parameters"]
                .as_array()
                .unwrap_or_else(|| panic!("claims/{name}/abi.json: `parameters` must be an array"))
                .clone();
            assert!(
                !params.is_empty(),
                "claims/{name}/abi.json: a claim exposes at least one public parameter"
            );
            for p in &params {
                assert_eq!(
                    p["visibility"].as_str(),
                    Some("public"),
                    "claims/{name}/abi.json: parameter {} is {:?}; a claim ABI is the public half of a Noir ABI and nothing else",
                    p["name"],
                    p["visibility"]
                );
            }
            ClaimAbi { name, params }
        })
        .collect()
}

// ------------------------------------------------------------- code gen ----

fn generate_claim_module(claim: &ClaimAbi) -> String {
    let name = &claim.name;
    let count = field_count(claim);

    let mut fields = String::new();
    let mut alloy_fields = String::new();
    let mut to_alloy = String::new();
    let mut from_alloy = String::new();
    let mut words = Vec::new();
    let mut decoded = String::new();
    let mut index = 0usize;
    for p in &claim.params {
        let field = p["name"].as_str().expect("ABI parameter name");
        let ty = &p["type"];
        fields.push_str(&format!("        pub {field}: {},\n", rust_type(ty, name)));
        alloy_fields.push_str(&format!(
            "            pub {field}: {},\n",
            alloy_type(ty, name)
        ));
        to_alloy.push_str(&format!(
            "                    {field}: {},\n",
            circuit_to_alloy(ty, &format!("value.{field}"))
        ));
        from_alloy.push_str(&format!(
            "                    {field}: {},\n",
            alloy_to_circuit(ty, &format!("value.{field}"))
        ));
        words.extend(leaves(ty, &format!("p.{field}"), name));
        decoded.push_str(&format!(
            "            {field}: {},\n",
            decode_expr(ty, index, name)
        ));
        index += leaves(ty, "_", name).len();
    }
    let words = words.join(",\n            ");
    let from_field = if decoded.contains("::from_field") {
        "        use outbe_zk_core::FieldElement;\n"
    } else {
        ""
    };

    format!(
        r#"/// The `{name}` claim, generated from `claims/{name}/abi.json`.
pub mod {name} {{
    use alloy_primitives::B256;
    use ark_bn254::Fr;

    /// The claim's directory name, as `l2/manifest.toml` spells it.
    pub const CLAIM_NAME: &str = "{name}";

    /// Number of public field words a proof of this claim exposes.
    pub const PUBLIC_INPUT_COUNT: usize = {count};

    /// Public inputs, in ABI order.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct PublicInputs {{
{fields}    }}

    /// Flatten to ABI-ordered field words — what a prover hands the backend
    /// and what `outbe_l2_zk_canonical::encode_combined_proof` takes.
    pub fn public_words(p: &PublicInputs) -> [Fr; PUBLIC_INPUT_COUNT] {{
        [
            {words},
        ]
    }}

    /// Rebuild the public inputs from ABI-ordered field words.
    ///
    /// The inverse of [`public_words`], and the half of decoding that needs no
    /// verification key. The other half — how many words a combined proof
    /// carries — comes from the key, so the decoder itself lives in
    /// `outbe-l2-zk-canonical` with the keys.
    pub fn from_fields(
        fields: &[Fr; PUBLIC_INPUT_COUNT],
    ) -> Result<PublicInputs, outbe_zk_core::Error> {{
{from_field}        Ok(PublicInputs {{
{decoded}        }})
    }}

    /// The same public inputs as Ethereum ABI values.
    pub mod alloy {{
        use alloy_primitives::B256;
        use ark_bn254::Fr;

        /// Public inputs, in ABI order.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct PublicInputs {{
{alloy_fields}        }}

        impl TryFrom<super::PublicInputs> for PublicInputs {{
            type Error = outbe_zk_core::Error;

            /// Reject field words that would not fit a 32-byte ABI value.
            fn try_from(value: super::PublicInputs) -> Result<Self, Self::Error> {{
                Ok(Self {{
{to_alloy}                }})
            }}
        }}

        impl TryFrom<PublicInputs> for super::PublicInputs {{
            type Error = outbe_zk_core::Error;

            /// Reject field words at or above the modulus instead of reducing.
            fn try_from(value: PublicInputs) -> Result<Self, Self::Error> {{
                Ok(Self {{
{from_alloy}                }})
            }}
        }}
    }}
}}

"#
    )
}

/// The table `outbe-l2-zk-canonical`'s build script reads the contract from.
/// `include_str!` rather than a copy: the bytes it checks a root's ABI against
/// are the committed file itself.
fn generate_claim_abis(claims: &[ClaimAbi]) -> String {
    let rows: String = claims
        .iter()
        .map(|c| {
            format!(
                "    crate::ClaimAbi {{\n\
                 \x20       name: {:?},\n\
                 \x20       abi_json: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/claims/{}/abi.json\")),\n\
                 \x20       public_input_count: {},\n\
                 \x20   }},\n",
                c.name,
                c.name,
                field_count(c),
            )
        })
        .collect();
    format!(
        "/// Every claim's ABI document, in claim-name order.\n\
         pub const CLAIM_ABIS: &[crate::ClaimAbi] = &[\n{rows}];\n"
    )
}

// ------------------------------------------------------------ ABI types ----

// ponytail: the generator handles `field`, unsigned `integer` and arrays of
// those — every shape a claim ABI uses today, plus the obvious next one. A
// claim that needs an EthAddress, a limbed `U256` or a multi-field struct as a
// public word gets a clear build failure here; lift the arms from
// `outbe-zk-canonical/build.rs`, which already has them, when one does.

/// Every leaf field word of one ABI parameter, as Rust expressions.
fn leaves(ty: &Value, expr: &str, claim: &str) -> Vec<String> {
    match ty["kind"].as_str() {
        Some("field") => vec![expr.to_string()],
        Some("integer") => vec![format!("Fr::from({expr} as u128)")],
        Some("array") => {
            let len = ty["length"].as_u64().expect("array length");
            (0..len)
                .flat_map(|i| leaves(&ty["type"], &format!("{expr}[{i}]"), claim))
                .collect()
        }
        _ => panic!("claim {claim:?}: unsupported public ABI type: {ty}"),
    }
}

/// Leaf count of a whole claim ABI.
fn field_count(claim: &ClaimAbi) -> usize {
    claim
        .params
        .iter()
        .map(|p| leaves(&p["type"], "_", &claim.name).len())
        .sum()
}

fn rust_type(ty: &Value, claim: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => "Fr".to_string(),
        Some("integer") => {
            let sign = ty["sign"].as_str().unwrap_or("unsigned");
            assert_eq!(
                sign, "unsigned",
                "claim {claim:?}: signed integers are not a public ABI type"
            );
            format!("u{}", ty["width"].as_u64().expect("integer width"))
        }
        Some("array") => {
            let inner = &ty["type"];
            assert!(
                matches!(inner["kind"].as_str(), Some("field" | "integer")),
                "claim {claim:?}: only arrays of field or integer are a public ABI type, got {inner}"
            );
            format!(
                "[{}; {}]",
                rust_type(inner, claim),
                ty["length"].as_u64().expect("array length")
            )
        }
        _ => panic!("claim {claim:?}: unsupported public ABI type: {ty}"),
    }
}

/// The same shape with field words as `B256`; integers keep their Rust type.
fn alloy_type(ty: &Value, claim: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => "B256".to_string(),
        Some("array") => format!(
            "[{}; {}]",
            alloy_type(&ty["type"], claim),
            ty["length"].as_u64().expect("array length")
        ),
        _ => rust_type(ty, claim),
    }
}

/// Convert one parameter to its Ethereum ABI form. Integers are identical in
/// both representations, so only field words need converting; `rust_type` has
/// already rejected anything else.
fn circuit_to_alloy(ty: &Value, expr: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => format!("outbe_zk_core::codec::field_to_b256(&{expr})?"),
        Some("array") if ty["type"]["kind"] == "field" => format!(
            "{{ let mut out = [B256::ZERO; {}]; \
             for (slot, value) in out.iter_mut().zip({expr}.iter()) {{ \
             *slot = outbe_zk_core::codec::field_to_b256(value)?; }} out }}",
            ty["length"].as_u64().expect("array length")
        ),
        _ => expr.to_string(),
    }
}

/// The reverse, rejecting field words at or above the modulus.
fn alloy_to_circuit(ty: &Value, expr: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => format!("outbe_zk_core::codec::field_from_b256(&{expr})?"),
        Some("array") if ty["type"]["kind"] == "field" => format!(
            "{{ let mut out = [Fr::from(0u64); {}]; \
             for (slot, value) in out.iter_mut().zip({expr}.iter()) {{ \
             *slot = outbe_zk_core::codec::field_from_b256(value)?; }} out }}",
            ty["length"].as_u64().expect("array length")
        ),
        _ => expr.to_string(),
    }
}

/// One parameter's value, rebuilt from `fields[..]` inside [`from_fields`].
fn decode_expr(ty: &Value, index: usize, claim: &str) -> String {
    match ty["kind"].as_str() {
        Some("field") => format!("fields[{index}]"),
        Some("integer") => format!("{}::from_field(&fields[{index}])?", rust_type(ty, claim)),
        Some("array") if ty["type"]["kind"] == "field" => {
            format!("std::array::from_fn(|i| fields[{index} + i])")
        }
        Some("array") => {
            let inner = &ty["type"];
            let stride = leaves(inner, "_", claim).len();
            let exprs: Vec<String> = (0..ty["length"].as_u64().expect("array length") as usize)
                .map(|i| decode_expr(inner, index + i * stride, claim))
                .collect();
            format!("[{}]", exprs.join(", "))
        }
        _ => panic!("claim {claim:?}: unsupported public ABI type: {ty}"),
    }
}
