//! Generate the demo's `Witness` type and circuit identity from the committed
//! root at `crates/outbe-l2-zk-canonical/l2/57005/tribute/1.0.0/`.
//!
//! Read-only: it parses the root's `abi.json`, hashes its `circuit.vk` and
//! checks the ACIR this crate carries against the root's `circuit.hash`. It
//! never runs `nargo` or `bb`, so `cargo test` needs no Noir toolchain.
//!
//! Only the parameter shapes the tribute root actually uses are handled —
//! `field`, a two-`Field` embedded-curve struct, and arrays of `u8` / `Field` /
//! `bool`. Anything else is a hard build failure rather than silently wrong
//! codegen; add the arm when a root needs it.

use std::fmt::Write as _;
use std::path::PathBuf;

use base64::Engine;
use serde_json::Value;
use tiny_keccak::{Hasher, Keccak};

/// The registered root this demo is the Rust side of.
const CHAIN_ID: u64 = 57005;
const CLAIM: &str = "tribute";
const VERSION: &str = "1.0.0";

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let root = manifest
        .join("../../crates/outbe-l2-zk-canonical/l2")
        .join(CHAIN_ID.to_string())
        .join(CLAIM)
        .join(VERSION);
    let root = root
        .canonicalize()
        .unwrap_or_else(|e| panic!("{root:?}: {e}"));

    let abi_path = root.join("abi.json");
    let vk_path = root.join("circuit.vk");
    let hash_path = root.join("circuit.hash");
    let bytecode_path = manifest.join("resources/bytecode.b64");
    for path in [&abi_path, &vk_path, &hash_path, &bytecode_path] {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed=build.rs");

    let abi: Value = serde_json::from_slice(&read(&abi_path)).expect("parse the root abi.json");
    let circuit_hash = hex32(
        std::str::from_utf8(&read(&hash_path))
            .expect("circuit.hash is utf-8")
            .trim(),
    );
    let vk_hash = keccak(&read(&vk_path));

    // The committed root carries no bytecode (L1 never needs it), so this crate
    // carries its own copy to prove with. Tie it to the root: a proof against
    // some other ACIR would not be a proof of the registered circuit.
    let bytecode = read(&bytecode_path);
    let acir = base64::engine::general_purpose::STANDARD
        .decode(std::str::from_utf8(&bytecode).expect("bytecode.b64 is utf-8"))
        .expect("bytecode.b64 is base64");
    assert_eq!(
        keccak(&acir),
        circuit_hash,
        "resources/bytecode.b64 is not the ACIR of {CHAIN_ID}/{CLAIM}/{VERSION}"
    );

    let params = abi["parameters"].as_array().expect("abi parameters");
    let mut out = String::from(
        "// @generated by build.rs from the committed root's abi.json.\n\
         // Do not edit; edit the root and rebuild.\n\n",
    );
    out.push_str(&generate(params, &circuit_hash, &vk_hash, &vk_path));
    std::fs::write(
        PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("demo_generated.rs"),
        out,
    )
    .expect("write demo_generated.rs");
}

fn read(path: &std::path::Path) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

fn keccak(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak::v256();
    let mut out = [0u8; 32];
    hasher.update(bytes);
    hasher.finalize(&mut out);
    out
}

fn hex32(hex: &str) -> [u8; 32] {
    assert_eq!(hex.len(), 64, "expected 64 hex chars, got {hex:?}");
    let mut out = [0u8; 32];
    for (index, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[index * 2..index * 2 + 2], 16).expect("hex");
    }
    out
}

fn byte_array(bytes: &[u8; 32]) -> String {
    let mut s = String::from("[");
    for byte in bytes {
        let _ = write!(s, "0x{byte:02x}, ");
    }
    s.push(']');
    s
}

/// One witness parameter, resolved to everything the generator needs.
struct Param {
    name: String,
    /// The circuit-side Rust type (`Fr`, `[u8; 64]`, …).
    rust: String,
    /// Statements pushing this parameter's field words onto `v`.
    flatten: String,
}

fn param(name: &str, ty: &Value) -> Param {
    let kind = ty["kind"].as_str().expect("parameter kind");
    let (rust, flatten) = match kind {
        "field" => ("Fr".into(), format!("v.push(w.{name});\n")),
        "struct" => {
            let members: Vec<&str> = ty["fields"]
                .as_array()
                .expect("struct fields")
                .iter()
                .map(|f| {
                    assert_eq!(f["type"]["kind"], "field", "only Field struct members");
                    f["name"].as_str().expect("member name")
                })
                .collect();
            assert_eq!(members, ["x", "y"], "only EmbeddedCurvePoint is handled");
            (
                "EmbeddedCurvePoint".into(),
                format!("v.push(w.{name}.x);\nv.push(w.{name}.y);\n"),
            )
        }
        "array" => {
            let len = ty["length"].as_u64().expect("array length") as usize;
            let element = &ty["type"];
            match element["kind"].as_str().expect("element kind") {
                "integer" => {
                    assert_eq!(element["width"], 8, "only u8 arrays are handled");
                    assert_eq!(element["sign"], "unsigned", "only u8 arrays are handled");
                    (
                        format!("[u8; {len}]"),
                        format!("for __b in w.{name} {{\n    v.push(Fr::from(__b as u64));\n}}\n"),
                    )
                }
                "boolean" => (
                    format!("[bool; {len}]"),
                    format!("for __b in w.{name} {{\n    v.push(Fr::from(__b as u64));\n}}\n"),
                ),
                "field" => (
                    format!("[Fr; {len}]"),
                    format!("for __f in w.{name} {{\n    v.push(__f);\n}}\n"),
                ),
                other => panic!("unhandled array element kind {other:?} for {name}"),
            }
        }
        other => panic!("unhandled parameter kind {other:?} for {name}"),
    };
    Param {
        name: name.to_string(),
        rust,
        flatten,
    }
}

fn generate(
    params: &[Value],
    circuit_hash: &[u8; 32],
    vk_hash: &[u8; 32],
    vk_path: &std::path::Path,
) -> String {
    // ACIR witness index order is `main()` declaration order: index `i` in the
    // flatten below is exactly ACIR `Witness(i)`. Public parameters take their
    // value from the claim's own `public_words`, so the prover and the on-chain
    // decoder share one flattener.
    let mut private = Vec::new();
    let mut flatten = String::new();
    let mut public_index = 0usize;
    for p in params {
        let name = p["name"].as_str().expect("parameter name");
        if p["visibility"] == "public" {
            let _ = writeln!(flatten, "v.push(__public[{public_index}]);");
            public_index += 1;
            continue;
        }
        let param = param(name, &p["type"]);
        flatten.push_str(&param.flatten);
        private.push(param);
    }

    format!(
        r#"use ark_bn254::Fr;

/// A Grumpkin point as the circuit's ABI carries it: two native field words.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EmbeddedCurvePoint {{
    pub x: Fr,
    pub y: Fr,
}}

/// The private witness, in ABI order.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Witness {{
{witness_fields}}}

/// Marker for the registered root `l2/{CHAIN_ID}/{CLAIM}/{VERSION}`.
///
/// Its [`CircuitId`](outbe_zk_core::zk::CircuitId) constants are the root's own
/// committed bytes; `tests/roundtrip.rs` asserts `VK_BYTES` equals
/// `l2_keys({CHAIN_ID}, Claim::{claim_variant})[0].vk_bytes`, so "proves against the
/// registered key" is checked, not asserted.
pub struct TributeDemo;

impl outbe_zk_core::zk::Circuit for TributeDemo {{
    type Witness = Witness;
    type PublicInputs = outbe_l2_zk_canonical::claims::{CLAIM}::PublicInputs;

    fn public_inputs(p: &Self::PublicInputs) -> Vec<Fr> {{
        outbe_l2_zk_canonical::claims::{CLAIM}::public_words(p).to_vec()
    }}

    fn witness_inputs(w: &Witness, p: &Self::PublicInputs) -> Vec<Fr> {{
        let __public = outbe_l2_zk_canonical::claims::{CLAIM}::public_words(p);
        let mut v: Vec<Fr> = Vec::new();
        {flatten}
        v
    }}
}}

impl outbe_zk_core::zk::CircuitId for TributeDemo {{
    const LABEL: &'static str = "l2.{CHAIN_ID}.{CLAIM}";
    const VERSION: &'static str = "{VERSION}";
    const CIRCUIT_HASH: [u8; 32] = {circuit_hash};
    const BYTECODE_B64: &'static str =
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/bytecode.b64"));
    const VK_BYTES: &'static [u8] = include_bytes!("{vk_path}");
    const VK_HASH: [u8; 32] = {vk_hash};
}}

"#,
        witness_fields = private
            .iter()
            .map(|p| format!("    pub {}: {},\n", p.name, p.rust))
            .collect::<String>(),
        claim_variant = "Tribute",
        circuit_hash = byte_array(circuit_hash),
        vk_hash = byte_array(vk_hash),
        vk_path = vk_path.display(),
    )
}
